### ISSUE TITLE
pip dependency conflict

### ISSUE THREAD

**Issue by sophwats** [rh-aiservices-bu/licence-plate-workshop#7]
Notebook 03, cell 1 when installing requirements.txt: 

ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
elyra-server 2.2.4 requires jinja2<3.0,>=2.11, but you have jinja2 3.0.1 which is incompatible.

**Comment by wkremser** [comment]
add this to the file requirements.txt to get it working again:

jinja2==2.11.3
beautifulsoup4==4.6.3
