### ISSUE TITLE
be more descriptive in the s2ibuild as to which version of python to use

### ISSUE THREAD

**Issue by erwangranger** [rh-aiservices-bu/licence-plate-workshop#9]
in [this page](https://github.com/rh-aiservices-bu/licence-plate-workshop/blob/main/docs/step6.md), modify the text and screenshot to make sure that the chosen image is python3.8-ubi7 .

**Comment by erwangranger** [comment]
Notes to myself for future reference. 

Currently, with python3.9-ubi8, the build fails with: 

```
ERROR: Could not find a version that satisfies the require...5.1, 2.5.2, 2.6.0, 2.6.1, 2.6.2, 2.7.0rc0, 2.7.0rc1, 2.7.0)
ERROR: No matching distribution found for tensorflow-gpu==2.4.1 (from -r requirements.txt (line 5))
WARNING: You are using pip version 19.3.1; however, version 21.3.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
error: build error: error building at STEP "RUN /usr/libexec/s2i/assemble": error while running runtime: exit status 1
```

that is due to this line: https://github.com/rh-aiservices-bu/licence-plate-workshop/blob/4ebb74326cdd70eedf861225f6604fef0d0e3194/requirements.txt#L5

rather than increasing the version of TensorFlow, for now, we'll keep the instructions as-is and instruct the user to keep choosing the python3.8-ubi7 builder image.

**Comment by erwangranger** [comment]
Hello @cfchase , can you review this issue and PR and merge if you agree?

**Comment by cfchase** [comment]
@erwangranger can we just update Tensorflow to 2.5.1?  That'll work in both versions of Python and it doesn't have all the CVEs in 2.4?

**Comment by erwangranger** [comment]
We could. I was not sure I wanted to open that can of worms, but if you say it'll work, we can do that.

**Comment by erwangranger** [comment]
This is fun: 

```
ERROR: tensorflow-gpu 2.5.1 has requirement h5py~=3.1.0, but you'll have h5py 2.10.0 which is incompatible.
ERROR: tensorflow-gpu 2.5.1 has requirement numpy~=1.19.2, but you'll have numpy 1.21.4 which is incompatible.
```

but then

```
ERROR: opencv-python-headless 4.5.4.60 has requirement numpy>=1.19.3, but you'll have numpy 1.19.2 which is incompatible.
ERROR: h5py 3.1.0 has requirement numpy>=1.19.3; python_version >= "3.9", but you'll have numpy 1.19.2 which is incompatible.
```

so pausing here for now.

**Comment by guimou** [comment]
You cannot update only one package. It's the full stack that has to be
checked for compatibility. And sometimes there is no solution. Especially
with Py39 as not every package has been released specifically for it.

**Comment by erwangranger** [comment]
Right. Thanks for the confirmation. 

For now, we'll be fixing only the instructions in order to pin the version of the builder image. 

Next time we revisit the workshop, we can do a bigger overhaul.
